
services:
  app_proxy:
    environment:
      APP_HOST: mediarr-homarr_server_1
      APP_PORT: 7575

  server:
    image: ghcr.io/homarr-labs/homarr:latest
    restart: on-failure
    environment:
      SECRET_ENCRYPTION_KEY: f2f7ed8e16e011bd827fd1dc8ac3b6d5de7d15ef04b4cad0e0f6f9a0a6952279
    volumes:
      - ${APP_DATA_DIR}/data:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
